"""Synthetic route/asset fixtures; no live generation, similarity or Office claims."""
import copy
from zipfile import ZipFile

import pytest
from PIL import Image, ImageDraw

from test_workflow import ref, respond, assertion
from common import read_json
from material_routes import validate_decision
import workflow as wf
from workflow_store import load, WorkflowError
from toolbox_manager.project_status import generation_routes, graph, reconcile, step_kind
from test_project_chain import project
from toolbox_manager import project_hub as hub


def decision(**patch):
    return {'basis':'low_similarity','reference':'input/slide-001.png','drawing':'assets/drawing.svg',
            'similarity_pct':72,'reason':'TEST Agent judgment: outline and proportions differ',**patch}


@pytest.mark.parametrize('score',[0, 72, 74.999])
def test_strictly_below_threshold_is_allowed(score):
    assert validate_decision(decision(similarity_pct=score))['similarity_pct']==score


@pytest.mark.parametrize('score',[75,75.001,100,-1,True,None,'72',float('nan'),float('inf'),10**400])
def test_threshold_and_invalid_scores_are_rejected(score):
    with pytest.raises(ValueError):validate_decision(decision(similarity_pct=score))


def test_user_request_can_skip_drawing_but_requires_reference_and_reason():
    data={'basis':'user_request','reference':'input/reference.png','reason':'User explicitly asked for generated icons'}
    assert validate_decision(data)==data
    with pytest.raises(ValueError):validate_decision({**data,'reason':''})
    with pytest.raises(ValueError):validate_decision({**data,'reference':'../private.png'})
    with pytest.raises(ValueError):validate_decision({**data,'basis':[]})


def make_project(tmp_path):
    p=tmp_path/'project';wf.start(p,[ref(tmp_path)])
    respond(p,{'regions':[{'id':'art','bbox':[0,0,640,360],'role':'diagram','summary':'SYNTHETIC illustration fixture'}]})
    (p/'assets').mkdir(exist_ok=True)
    (p/'assets/drawing.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" width="100" height="50"><rect width="45" height="45" fill="red"/></svg>','utf-8')
    return p


def request(data=None, **patch):
    return {'action':'request_asset','request':{'id':'artwork','purpose':'SYNTHETIC pair of icons',
        'prompt':'Reference guided separate icons with transparent gutters, no labels',
        'transparent':True,'allowed_approximation':True,'multi_icon_sheet':True,
        'generation_decision':decision() if data is None else data,**patch}}


def projection(p):
    state=load(p)
    return {'phase':{'stage':'production','status':'running'},
            'activity':{'generation_routes':generation_routes(state),'calls':[]}}


def test_request_validation_is_atomic_and_requires_real_drawing(tmp_path):
    p=make_project(tmp_path);task=wf.next_task(p)
    for data in [decision(similarity_pct=75),decision(drawing='assets/missing.svg')]:
        with pytest.raises(WorkflowError):respond(p,request(data),task)
        assert load(p)['asset_jobs']==[]
        assert wf.next_task(p)['task']['id']==task['task']['id']
    with pytest.raises(WorkflowError):respond(p,request(transparent=False),task)
    assert not load(p)['asset_jobs']


def test_request_graph_and_two_crops_survive_scene_freeze_and_ppt_build(tmp_path):
    p=make_project(tmp_path)
    respond(p,request())
    pending=projection(p);nodes=graph(pending)['nodes']
    assert [n['kind'] for n in nodes if n.get('route_job')]==['material','fidelity','generation','crop','compose']
    assert next(n for n in nodes if n.get('kind')=='fidelity')['status_label']=='Agent 72%'
    assert next(n for n in nodes if n.get('kind')=='generation')['status']=='planned'
    assert not any(n['status']=='blocked' for n in nodes)
    from asset_ops import prepare_generation
    handoff=prepare_generation(p,tmp_path/'handoff')
    assert handoff['generation_decision']==decision()
    assert handoff['output_contract']['multi_icon_sheet'] is True
    assert handoff['generation_reference']==str((p/'input/slide-001.png').resolve())
    assert str((p/'assets/drawing.svg').resolve()) in {r['file'] for r in handoff['reference_files']}
    sheet=tmp_path/'synthetic-sheet.png';image=Image.new('RGBA',(100,50),(0,0,0,0))
    d=ImageDraw.Draw(image);d.rectangle([5,5,40,40],fill='red');d.ellipse([60,5,95,40],fill='blue');image.save(sheet)
    respond(p,{'file':str(sheet),'tool_used':'synthetic-test-fixture','provenance':'Locally authored test fixture; not generated by AI'})
    state=load(p);asset=state['asset_catalog'][-1]
    assert asset['generation_decision']==decision()
    assert next(n for n in graph(projection(p))['nodes'] if n.get('kind')=='generation')['status_label']=='素材已登记'
    objects=[];decisions=[]
    for i in range(2):
        objects.append({'id':'icon'+str(i),'kind':'image','asset':asset['asset'],'source_kind':'generated',
            'asset_role':'icon','raster_content':'generated_illustration','raster_reason':'TEST: Agent judged outline similarity below threshold',
            'generation_decision':decision(),'provenance':'Synthetic fixture, not a model result','bbox':[40+i*160,40,100,100],
            'source_crop':[i*50,0,50,50],'fit':'stretch'})
        decisions.append({'target_id':'icon'+str(i),'route':'generated','generation_considered':True,
            'reason':'Synthetic fallback decision fixture','remaining_risk':'Visual and Office review not run'})
    payload={'objects':objects,'source_notes':'Synthetic transparency/crop fixture','asset_decisions':decisions}
    respond(p,payload)
    nodes=graph(projection(p))['nodes']
    assert next(n for n in nodes if n.get('kind')=='crop')['status_label']=='裁剪已登记'
    assert next(n for n in nodes if n.get('route_job') and n.get('kind')=='compose')['status_label']=='回装已登记'
    t=wf.next_task(p);assert t['task']['kind']=='source_review'
    respond(p,assertion(t),t)
    t=wf.next_task(p)
    state=load(p);run=p/state['run']['dir']
    assert (run/'assets/drawing.svg').is_file()
    from validate_scene import validate
    assert not validate(read_json(run/'scene.json'),run)
    from build_pptx import build
    deck=tmp_path/'fixture.pptx';build(run/'scene.json',deck)
    with ZipFile(deck) as z:
        from lxml import etree
        xml=etree.fromstring(z.read('ppt/slides/slide1.xml'))
        assert len(xml.xpath('//*[local-name()="pic"]'))==2
        assert len(xml.xpath('//*[local-name()="srcRect"]'))==2


def test_generation_exception_does_not_allow_logo_or_missing_decision(tmp_path):
    from material_routes import generated_illustration
    base={'source_kind':'generated','raster_content':'generated_illustration','asset_role':'icon','generation_decision':decision()}
    for patch in [{'asset_role':'logo'},{'source_kind':'crop'},{'generation_decision':None}]:
        with pytest.raises(ValueError):generated_illustration({**base,**patch})


def test_active_material_failure_is_shown_without_changing_completed_route_nodes():
    route={'id':'job','purpose':'test','decision':decision(),'status':'pending','multi_icon_sheet':True,'placed':0,'cropped':0,'task_id':'material-task'}
    failure={'id':'failed','status':'outcome_unknown','tool':'workflow.submit','task_id':'material-task','evidence_id':'audit-test'}
    state={'activity':{'generation_routes':[route],'calls':[failure],'issues':reconcile([], [failure])}}
    nodes=graph(state)['nodes']
    assert sum(n['status']=='outcome_unknown' for n in nodes)==1
    assert next(n for n in nodes if n.get('route_job') and n['kind']=='generation')['status']=='outcome_unknown'
    assert next(n for n in nodes if n.get('kind')=='fidelity')['status']=='done'
    assert step_kind('workflow.submit','asset_material')=='generation'
    assert step_kind('assets.crop')=='crop'


def test_user_direct_generation_has_no_invented_drawing_and_custom_graph_stays_owned():
    route={'id':'user-job','purpose':'test','decision':{'basis':'user_request','reference':'input/ref.png','reason':'User requested direct generation'},
        'status':'pending','multi_icon_sheet':False,'placed':0,'cropped':0,'task_id':None}
    state={'activity':{'generation_routes':[route]}}
    view=graph(state)['nodes']
    assert not any(n.get('route_job') and n['kind']=='material' for n in view)
    assert next(n for n in view if n.get('kind')=='fidelity')['status_label']=='用户指定'
    state['work_graph']={'nodes':[{'id':'mine','title':'My plan','status':'planned','after':[]}]}
    assert len(graph(state)['nodes'])==1


def test_project_observer_collects_generation_route_and_prompt_exposes_policy(project):
    manager,p,key=project
    from scripts.project_journal import read_json as load_json
    from common import write_json
    state=load_json(p/'workflow/state.json',{})
    row=manager.store.get('workbench_projects',{})[key]
    state.update(project_id=row['project_id'],revision=0,status='awaiting_asset_generation',pages=[],history=[])
    state['asset_jobs']=[{'id':'fixture-job','slide_id':'page1','status':'pending','request':request()['request']}]
    write_json(p/'workflow/state.json',state)
    result=hub.observe(manager,key)
    assert result['activity']['generation_routes'][0]['decision']['similarity_pct']==72
    assert any(n.get('kind')=='generation' for n in hub.snapshot(manager,key)['display_graph']['nodes'])
    from toolbox_manager.material_policy import effective
    policy=effective(manager,p)
    assert policy['illustration_route']['threshold_pct']==75
    from toolbox_manager.production_storage import startup_prompt
    assert '75%' in startup_prompt(manager)['text']
