import {releaseView} from './release-view.js';
import {mountSoftwareUpdate,stopSoftwareUpdate} from './software-update.js';
import {mountPPTAgent} from './pptagent-settings.js';
import {mountUsage,stopUsage,usageMap,usageLink,track} from './usage.js';
import {mountOverview,stopOverview,saveOverview} from './overview.js';
import {mountPreparation,stopPreparation,mountPreparedList} from './preparation.js';
import {mountProjectDetails,stopProjectDetails} from './project-details.js';
import {mountGraphics,stopGraphics} from './graphics.js';
import {mountAgentSetup} from './agent-setup.js';
import {startAgentLive} from './agent-live.js';
import {mountIcons,stopIcons} from './icons.js';
import {api,upload,download,copy} from './api.js';
import {mountWorkbench,stopWorkbench,refreshWorkbench} from './project-chain.js';
import {mountProjects,stopProjects} from './projects.js';
import {mountLearning,stopLearning} from './experience.js';
const paths={
 overview:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',
 skills:'M5 3h10l4 4v14H5zM14 3v5h5M8 12h8M8 16h6',
 tools:'M14 7l3-3a5 5 0 0 0-6 6L4 17a2.1 2.1 0 0 0 3 3l7-7a5 5 0 0 0 6-6l-3 3z',
 plugins:'M8 3v4M16 3v4M5 7h14v6l-4 4v4H9v-4l-4-4z',
 updates:'M20 10a8 8 0 0 0-14-5L3 8M3 3v5h5M4 14a8 8 0 0 0 14 5l3-3M16 16h5v5',
 logs:'M5 3h14v18H5zM8 7h8M8 11h8M8 15h5',
 settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8zM9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1z',
 docs:'M3 4h7l2 2 2-2h7v16h-7l-2 1-2-1H3zM12 6v15',
 search:'M10.5 3a7.5 7.5 0 1 0 0 15 7.5 7.5 0 0 0 0-15zM16 16l5 5',
 plus:'M12 5v14M5 12h14',arrow:'M5 12h14M14 7l5 5-5 5',chevron:'M9 5l7 7-7 7',copy:'M8 8h12v13H8zM16 8V3H3v13h5',
 close:'M6 6l12 12M6 18L18 6',check:'M5 12l4 4L19 6',info:'M12 8v.1M12 11v6M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20z',
 download:'M12 3v12M7 10l5 5 5-5M4 16v5h16v-5',upload:'M12 16V3M7 8l5-5 5 5M4 16v5h16v-5',shield:'M12 2l8 3v7c0 5-8 10-8 10S4 17 4 12V5zM8 12l3 3 5-6',
 code:'M8 7l-5 5 5 5M16 7l5 5-5 5M14 4l-4 16',box:'M3 7l9-5 9 5v10l-9 5-9-5zM3 7l9 5 9-5M12 12v10',clock:'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20zM12 6v6l4 2',restore:'M3 3v6h6M3 9a9 9 0 1 1 0 7',edit:'M14 4l6 6M4 20l4-1L21 6l-3-3L5 16z'};
const icon=n=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[n]||paths.box}"/></svg>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const badge=(text,color='')=>`<span class="tag ${color}">${esc(text)}</span>`;
const notice=(text,warn=false)=>`<div class="notice${warn?' warn':''}">${icon('info')}<span>${esc(text)}</span></div>`;
const btn=(text,action,extra='',cls='')=>`<button class="${cls}" data-action="${action}" ${extra}>${text}</button>`;
const head=(title,desc,actions='')=>`<div class="page-head"><div><h1>${title}</h1><div class="subtitle">${desc}</div></div><div class="actions">${actions}</div></div>`;
const panel=(title,body,actions='')=>`<section class="panel section"><div class="panel-head"><h2>${title}</h2><div class="actions">${actions}</div></div>${body}</section>`;
const switcher=(on,action,attrs='',label='启用')=>`<label class="switch"><input type="checkbox" role="switch" aria-label="${esc(label)}" data-change="${action}" ${attrs} ${on?'checked':''}><span class="track"></span></label>`;
const code=t=>`<pre class="codebox">${esc(t)}</pre>`;
const time=t=>new Date(t).toLocaleString('zh-CN',{hour12:false});
let unsavedChanges=false,pendingNavigation='',lastLocation=location.hash||'#/overview';
let boot,bootLoading,route='overview',items=[],selected=null,filter='',kind='all',page=0,tab='tools',documents=[],docPath='manager_docs/USER_GUIDE.md',docPackage=null,doc=null,editing=false,settings=null,importPlan=null,integrationPlan=null,commandEditing=null,docHistory=false,renderGeneration=0;
const main=document.querySelector('#main'),dialog=document.querySelector('#dialog');
const navs=[['overview','概况'],['projects','项目'],['workbench','制作工作台'],['pptagent','Agent 接入'],['icons','素材库'],['learning','经验库'],['usage','使用统计'],['skills','Skill 管理'],['tools','工具与指令'],['plugins','插件与接入'],['updates','版本与更新'],['logs','运行日志'],['settings','设置'],['docs','帮助'],['create','新建制作'],['graphics','图形构造']];
const primaryNav=[['overview','概况','overview'],['projects','项目','box'],['icons','素材库','overview'],['learning','经验库','docs'],['usage','使用统计','clock'],['pptagent','Agent 接入','plugins']];
 document.querySelector('#navigation').innerHTML=primaryNav.map(([id,label,i])=>`<a href="#/${id}" data-route="${id}">${icon(i)}<span>${label}</span></a>`).join('');
 document.querySelector('#bottom-navigation').innerHTML=[['docs','帮助'],['settings','设置']].map(([id,label])=>`<a href="#/${id}" data-route="${id}">${icon(id)}<span>${label}</span></a>`).join('');
document.querySelector('#refresh-button').innerHTML=icon('updates');
function toast(t,error=false){const e=document.querySelector('#toast');e.textContent=t;e.className=(error?'error ':'')+'visible';clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.className='',4500);}
function modal(title,body,foot=''){document.querySelector('#dialog-content').innerHTML=`<div class="dialog-head"><h2>${esc(title)}</h2>${btn(icon('close'),'close','','icon-button')}</div><div class="dialog-body">${body}</div><div class="dialog-foot">${btn('关闭','close')}${foot}</div>`;if(!dialog.open)dialog.showModal();}
async function reloadBoot(){boot=await api('boot');document.documentElement.dataset.theme=boot.settings.theme;document.querySelector('#side-version').textContent='版本 '+boot.version;document.querySelector('#footer-version').textContent='PPT Toolbox '+boot.version;}
async function render(){
 const rendering=++renderGeneration;
 stopWorkbench();stopPreparation();stopProjectDetails();stopGraphics();
 stopIcons();
 stopLearning();stopUsage();stopSoftwareUpdate();
 stopProjects();stopOverview();main.onclick=null;
 route=location.hash.replace('#/','').split('?')[0];if(!navs.some(n=>n[0]===route))route='overview';
 document.querySelectorAll('nav a').forEach(x=>x.classList.toggle('active',x.dataset.route===(['workbench','create'].includes(route)?'projects':route==='graphics'?'icons':['skills','tools','plugins','updates','logs'].includes(route)?'settings':route)));document.querySelector('#breadcrumb').textContent=navs.find(x=>x[0]===route)[1];document.querySelector('#sidebar').classList.remove('open');
 try{
  const ready=boot?Promise.resolve(boot):(bootLoading ||= reloadBoot().then(()=>boot).finally(()=>bootLoading=null));
  if(!['projects','workbench','pptagent'].includes(route))await ready;else ready.catch(()=>{});
  if(rendering!==renderGeneration)return;
  const mounts={workbench:()=>mountWorkbench(main),icons:()=>mountIcons(main),
   projects:async()=>{await mountProjects(main,ready);if(rendering===renderGeneration)mountPreparedList(main);},
   pptagent:async()=>{main.innerHTML=head('Agent 接入','驻留 PPTAgent 使用 Responses API，负责整理记录与管理任务。')+`<div id="pptagent-host"></div><p class="small muted">模型会接收任务文字、相关项目记录和工具结果。<a href="#/settings?section=agent">配置 Codex 等制作 Agent 的 MCP 接入</a></p>`;await mountPPTAgent(main.querySelector('#pptagent-host'));},
   create:()=>mountPreparation(main,boot),graphics:()=>mountGraphics(main),usage:()=>mountUsage(main),learning:()=>mountLearning(main,{icon}),
   overview,tools,skills,docs,plugins,updates,logs,settings:settingPage};
  await mounts[route]();
  if(rendering===renderGeneration&&['settings','skills','tools','plugins','updates','logs'].includes(route))settingsNavigation();
 }catch(e){if(rendering===renderGeneration)main.innerHTML=`<div class="error-banner"><strong>当前操作无法完成</strong><p>${esc(e.message)}</p>${btn('重新连接','refresh')}</div>`;}
}
const settingsLinks=[['settings','常规与权限'],['settings?section=agent','制作 Agent 接入'],['skills','制作规则'],['tools','工具与指令'],['updates','软件与扩展包'],['plugins','插件来源'],['logs','日志']];
function settingsNavigation(){
 if(route==='settings'&&(!main.querySelector('#agent-setup')||!main.querySelector('.setting-grid')))return;
 main.querySelector('.settings-navigation')?.remove();
 main.insertAdjacentHTML('afterbegin',`<nav class="section-nav settings-navigation" aria-label="设置分类">${settingsLinks.map(([r,label])=>`<a href="#/${r}" class="${location.hash==='#/'+r?'active':''}">${label}</a>`).join('')}</nav>`);
 if(route==='settings'){
  const agent=new URLSearchParams(location.hash.split('?')[1]||'').get('section')==='agent';
  for(const panel of main.querySelectorAll('.section'))panel.hidden=agent;
  main.querySelector('#agent-setup').hidden=!agent;main.querySelector('.setting-grid').hidden=agent;
  if(agent)main.querySelector('[data-action="save-settings"]')?.setAttribute('hidden','');
  if(agent){main.querySelector('h1').textContent='制作 Agent 接入';main.querySelector('.page-head .subtitle').innerHTML='为 Codex 等客户端配置 MCP。驻留 PPTAgent 的 API 在<a href="#/pptagent">左侧 Agent 接入页</a>配置。';}
 }
}
async function overview(){await mountOverview(main,boot,value=>unsavedChanges=value);}
async function tools(){
 const counts=await usageMap('tool');items=(await api('tools')).map(t=>({...t,usage:counts[t.id]}));if(!selected||!items.some(i=>i.id===selected))selected=items[0]?.id;
 main.innerHTML=head('工具与指令','按用途查找能力，查看真实调用入口，并管理 Agent 通过本工具箱可用的指令。',btn(icon('plus')+'新建自定义指令','new-command','','primary'))+
 `<div class="tabs"><button data-action="tool-tab" data-tab="tools" class="${tab==='tools'?'active':''}">工具目录 <span class="count">${items.length}</span></button><button data-action="tool-tab" data-tab="commands" class="${tab==='commands'?'active':''}">自定义指令</button></div>`+
 (tab==='commands'?'<div id="custom-commands"></div>':`<div class="toolbar"><div class="search">${icon('search')}<input id="tool-search" aria-label="搜索工具与指令" placeholder="搜索名称、用途、函数或参数…" value="${esc(filter)}"></div><select id="tool-kind" aria-label="工具类型"><option value="all">全部类型</option><option value="python">Python 脚本</option><option value="powershell_module">PPT 原生指令</option><option value="powershell">PowerShell 脚本</option><option value="host">宿主能力</option><option value="manual">操作手册</option></select><span class="grow"></span><span class="muted tiny">开关作用于受管入口</span></div><div class="tool-layout"><div class="panel" id="tool-list"></div><aside class="panel inspector" id="tool-detail"></aside></div>`);
 if(tab==='commands'){await commandList();return;}
 document.querySelector('#tool-kind').value=kind;paintToolList();await toolDetail();
 document.querySelector('#tool-search').addEventListener('input',e=>{filter=e.target.value;page=0;paintToolList();});document.querySelector('#tool-kind').addEventListener('change',e=>{kind=e.target.value;page=0;paintToolList();});
}
function filtered(){let q=filter.toLowerCase();return items.filter(t=>(kind==='all'||t.kind===kind)&&JSON.stringify(t).toLowerCase().includes(q));}
function paintToolList(){const all=filtered();page=Math.max(0,Math.min(page,Math.ceil(all.length/10)-1));const list=all.slice(page*10,page*10+10);
 document.querySelector('#tool-list').innerHTML=`<table class="tool-table"><thead><tr><th>工具 / 指令</th><th class="kind-col">类型</th><th>启用</th></tr></thead><tbody>${list.map(t=>`<tr data-action="select-tool" data-id="${esc(t.id)}" class="${selected===t.id?'selected':''}" tabindex="0"><td><div class="tool-name">${esc(t.title)}</div><div class="tool-id mono">${esc(t.id)}</div>${usageLink('tool',t.id,t.usage)}</td><td class="kind-cell">${badge(t.kind_label)}</td><td>${switcher(t.enabled,'toggle-tool',`data-id="${esc(t.id)}"`,(t.enabled?'停用':'启用')+' '+t.title)}</td></tr>`).join('')}</tbody></table>${!list.length?'<div class="empty">没有匹配的工具。可尝试搜索「透明」「半圆」或「字体」。</div>':''}<div class="table-foot"><span>共 ${all.length} 项 · 第 ${page+1} / ${Math.max(1,Math.ceil(all.length/10))} 页</span><div class="actions">${btn('上一页','prev-tools',page===0?'disabled':'')}${btn('下一页','next-tools',(page+1)*10>=all.length?'disabled':'')}</div></div>`;
}
async function toolDetail(){if(!selected){document.querySelector('#tool-detail').innerHTML='<div class="empty">选择工具查看调用方式</div>';return;}const t=await api('tool',undefined,{id:selected});window.currentTool=t;
 document.querySelector('#tool-detail').innerHTML=`<div class="inspector-top"><div class="label-line"><span class="row-icon">${icon(t.kind==='manual'?'docs':'code')}</span>${badge(t.kind_label,'blue')}</div><div class="inspector-title">${esc(t.title)}</div><div class="mono muted tiny">${esc(t.id)}</div></div><div class="inspector-body"><div class="field"><span class="field-label">实际入口</span><div class="field-value mono">${esc(t.entry||'由宿主发现真实工具')}</div>${t.functions?`<div class="field-value mono">${esc(t.functions.join(', '))}</div>`:''}</div><div class="field"><span class="field-label">输入参数</span><div class="field-value mono">${esc(t.inputs)}</div></div><div class="field"><span class="field-label">返回结果</span><div class="field-value">${esc(t.outputs)}</div></div><div class="field"><span class="field-label">可用性</span><div class="field-value">${esc(t.availability)}</div></div><div class="field"><span class="field-label">使用条件与限制</span><div class="field-value muted">${esc(t.limitations)}</div></div>${t.kind==='python'||t.kind==='powershell'?btn(icon('copy')+'复制受管调用示例','copy-tool','','primary'):btn(icon('copy')+'复制入口与说明','copy-tool')} ${t.entry?btn(icon('code')+'查看源代码','view-source'):''} ${(t.manuals||[]).map(p=>btn(icon('docs')+'打开相关手册','open-doc',`data-path="${esc(p)}"`)).join('')}</div>`;
}
async function commandList(){const list=await api('commands');window.customCommands=list;document.querySelector('#custom-commands').innerHTML=notice('自定义指令是可复制、可由 Agent 读取的文本模板。保存不会执行命令，也不会自动写入其他 Agent 的系统指令。')+'<div class="spacer"></div>'+ (list.length?list.map(x=>panel(esc(x.title),`<div class="panel-body"><p class="small muted">${esc(x.description)}</p><pre class="command-body">${esc(x.body)}</pre><div class="actions">${badge(x.enabled?'对受管上下文可见':'已停用',x.enabled?'green':'')}${btn(icon('edit')+'编辑','edit-command',`data-id="${x.id}"`)}${btn(icon('copy')+'复制','copy-command',`data-id="${x.id}"`)}</div></div>`)).join(''):`<div class="panel empty">${icon('code')}<strong>保存经常使用的调用指令</strong><p>例如安装检查、生成透明素材、最终验收等模板。</p>${btn(icon('plus')+'新建指令','new-command','','primary')}</div>`);}
function commandModal(c=null){commandEditing=c;modal(c?'编辑自定义指令':'新建自定义指令',`<label for="cmd-title">名称</label><input id="cmd-title" value="${esc(c?.title||'')}" placeholder="例如：安装后环境检查"><label for="cmd-description">用途说明</label><input id="cmd-description" value="${esc(c?.description||'')}" placeholder="告诉 Agent 什么时候使用"><label for="cmd-body">指令内容</label><textarea id="cmd-body" class="editor" style="min-height:220px" placeholder="写入需要复用的指令…">${esc(c?.body||'')}</textarea><label class="switch"><input id="cmd-enabled" type="checkbox" ${c?.enabled===0?'':'checked'}><span class="track"></span><span>对受管 Agent 上下文可见</span></label>`,btn('保存指令','save-command','','primary'));}
async function skills(){const p=await api('packages');main.innerHTML=`<div class="rule-shortcuts"><a href="#/docs?path=SKILL.md">Skill 与用户覆盖</a><a href="#/docs?path=${encodeURIComponent('给模型的启动指令.txt')}">制作指令模板</a><a href="#/docs?path=manager_docs/USER_GUIDE.md">当前版使用说明</a></div>`+head('Skill 管理','管理内置制作规则与独立扩展，用户指令单独保存。',btn(icon('upload')+'管理扩展工具包','go-updates','','primary'))+
 `<div class="panel section">${p.map(packageRow).join('')}</div>`+
 panel('当前版本的指令维护',`<div class="panel-body"><div class="two-col"><div><h3>保留原版，单独保存用户修改</h3><p class="small muted">编辑 SKILL.md 或相关规则后，修改存入管理数据库，通过受管上下文与手册读取生效。可以比较差异、恢复原版或历史版本。</p><p class="small muted">直接读取旧安装副本的 Agent 不会自动获得这里的覆盖。切换包版本后，用户覆盖保留在原版本中，需要人工合并。</p></div><div class="quick-links">${btn(icon('edit')+'编辑当前 Skill 指令','open-doc','data-path="SKILL.md"')}${btn(icon('docs')+'查看素材决策规则','open-doc','data-path="references/asset-policy.md"')}${btn(icon('docs')+'查看对照与验收规则','open-doc','data-path="references/rendering-and-review.md"')}</div></div></div>`)+notice('这里的启停约束管理器、受管 CLI 与 MCP。它不会改动 Codex 已有 config.toml，也不是防止直接运行脚本的安全边界。');}
function packageRow(p){return `<div class="package-row"><div class="package-icon">${icon('box')}</div><div class="list-main"><div class="package-title"><strong>${esc(p.source==='builtin'?'内置 PPT 制作工具':p.name)}</strong>${p.source==='builtin'?badge('随软件更新'):badge('v'+p.version,'blue')}${p.active?badge('当前版本','green'):''}</div><p class="package-description">${esc(p.description)}</p>${p.source!=='builtin'&&p.compatibility?`<p class="small muted">${esc(p.compatibility.message)}</p>`:''}<div class="actions">${badge(p.source==='builtin'?'内置工具':'独立扩展')}${badge(p.trusted?'来源已信任':'未信任',p.trusted?'':'amber')}</div><p class="package-path mono">${esc(p.path)}</p></div><div class="package-buttons">${switcher(p.enabled,'toggle-package',`data-id="${esc(p.id)}"`,(p.enabled?'停用':'启用')+'工具包 '+p.version)}${!p.trusted?btn('确认来源可信','trust-package',`data-id="${esc(p.id)}"`):''}${!p.active?btn('查看规则','open-doc',`data-path="SKILL.md" data-package="${esc(p.id)}"`):''}${!p.active?btn('切换到此版本','activate-package',`data-id="${esc(p.id)}"`):btn('查看指令','open-doc','data-path="SKILL.md"')}</div></div>`;}
function md(text){
 const source=text.replace(/^---\n[\s\S]*?\n---\n/,'');let lines=source.split('\n'),out=[],pre=false,buf=[],table=[];
 const inline=s=>esc(s).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');
 const endTable=()=>{if(table.length){out.push('<table>'+table.filter(l=>!/^\|?\s*[-:]+[\s|:\-]*$/.test(l)).map((l,i)=>'<tr>'+l.replace(/^\||\|$/g,'').split('|').map(c=>`<${i?'td':'th'}>${inline(c.trim())}</${i?'td':'th'}>`).join('')+'</tr>').join('')+'</table>');table=[];}};
 for(const line of lines){if(line.startsWith('```')){endTable();if(pre){out.push('<pre>'+esc(buf.join('\n'))+'</pre>');buf=[];}pre=!pre;continue;}if(pre){buf.push(line);continue;}if(line.trim().startsWith('|')){table.push(line);continue;}endTable();if(/^#{1,3} /.test(line)){const n=line.match(/^#+/)[0].length;out.push(`<h${n}>${inline(line.slice(n+1))}</h${n}>`);}else if(/^[-*] |^\d+\. /.test(line))out.push('<div class="md-list">'+inline(line)+'</div>');else if(line.trim())out.push('<p>'+inline(line)+'</p>');}endTable();if(pre)out.push('<pre>'+esc(buf.join('\n'))+'</pre>');return out.join('');
}
async function docs(){docPackage=docPackage||boot.active.id;const requestedDoc=new URLSearchParams(location.hash.split('?')[1]||'').get('path');if(requestedDoc)docPath=requestedDoc;documents=await api('docs',undefined,{package_id:docPackage});if(!documents.some(d=>d.path===docPath))docPath=documents[0]?.path;
 main.innerHTML=head('说明书与指令','按需查看手册；用户覆盖独立保存，可比较差异并恢复历史版本。',`<select id="doc-package" aria-label="选择说明书所属工具包">${boot.packages.map(p=>`<option value="${esc(p.id)}" ${p.id===docPackage?'selected':''}>${p.source==='builtin'?'内置制作工具 · 随软件更新':esc(p.name)+' · '+esc(p.version)}${p.id===boot.active.id?'（当前使用）':''}</option>`).join('')}</select>`)+`<div class="section-nav rule-shortcuts" aria-label="常用帮助"><a href="#/docs?path=manager_docs/USER_GUIDE.md">开始使用</a><a href="#/docs?path=manager_docs/PROJECT_MANAGEMENT.md">排序、批量与归档</a><a href="#/docs?path=manager_docs/PPTAGENT.md">PPTAgent 接入</a><a href="#/docs?path=manager_docs/USAGE_COUNTS.md">使用统计口径</a></div><label class="doc-search">搜索说明书<input type="search" id="doc-search" placeholder="查找项目管理、Agent 接入或使用统计"></label><div class="doc-layout"><aside class="panel doc-list">${documents.map(d=>`<a href="#/docs" class="doc-link ${d.path===docPath?'active':''}" data-action="select-doc" data-path="${esc(d.path)}">${esc(d.title)}${d.customized?' <span class="tag blue">用户覆盖</span>':''}<small>${esc(d.path)}</small></a>`).join('')}</aside><section class="panel" id="doc-panel"></section></div>`;await docView();document.querySelector('#doc-search').oninput=e=>document.querySelectorAll('.doc-link').forEach(a=>a.hidden=!a.textContent.toLowerCase().includes(e.target.value.toLowerCase()));document.querySelector('#doc-package').addEventListener('change',async e=>{docPackage=e.target.value;docPath='SKILL.md';editing=false;await docs();});}
async function docView(){if(!docPath){document.querySelector('#doc-panel').innerHTML='<div class="empty">此包没有可读手册</div>';return;}doc=await api('doc',undefined,{path:docPath,package_id:docPackage});document.querySelector('#doc-panel').innerHTML=`<div class="panel-head"><div><h2>${esc(doc.path)}</h2><div class="tiny muted" style="margin-top:6px">${doc.customized?'用户覆盖 · 修订 '+doc.revision:'随包版本 · 尚无用户覆盖'}</div></div><div class="actions">${btn(icon('copy'),'copy-doc','aria-label="复制文档"','icon-button')}${doc.editable?btn(editing?'退出编辑':'编辑用户覆盖','edit-doc'):''}</div></div><div class="panel-body">${doc.base_changed?notice('随包原文已更新，当前用户覆盖需要核对。请比较差异，合并后保存；也可恢复随包原版。',true):''}${editing?notice('保存到当前版本的用户覆盖，不修改原始安装文件。通过管理器上下文与手册接口生效。')+'<div class="spacer"></div>'+`<textarea id="doc-editor" class="editor" aria-label="指令编辑器">${esc(doc.content)}</textarea><div class="actions" style="margin-top:15px">${btn('保存修改','save-doc','','primary')}${btn('比较原版差异','diff-doc')}${btn('恢复与历史','history-doc')}</div>`:`<article class="markdown">${md(doc.content)}</article>`}</div>`;}
async function plugins(){const i=await api('integration');window.integration=i;main.innerHTML=head('插件与 Agent 接入','生成本机可用的 Skill / MCP 配置，或将工具箱注册为 Codex 本地插件来源。',btn(icon('download')+'导出接入配置','export-integration','','primary'))+
 `<div class="two-col"><div>${panel('Codex 本地插件',`<div class="panel-body"><div class="status-line"><span class="package-icon">${icon('plugins')}</span><div><h3 style="margin-bottom:6px">PPT Toolbox Manager</h3>${badge(i.registration?'来源已注册 · 宿主待验证':'尚未注册本地来源',i.registration?'blue':'')}</div></div><p class="small muted">MCP 已包含受管重建、局部修改、比较与采用。项目写入受执行开关和目录授权控制，其他登记工具保留受管 CLI 入口。</p><div class="spacer"></div>${notice('注册只更新本机 marketplace.json 中本插件的来源，其他条目保留并备份。不会自动安装、启用插件或改动 config.toml。')}<div class="spacer"></div>${btn('预览注册变更','register-plan','','primary')}${i.registration?`<div class="field" style="margin-top:20px"><span class="field-label">已登记来源</span><div class="field-value mono">${esc(i.registration.source)}</div></div>`:''}</div>`)}
 ${panel('通用 MCP 接入',`<div class="panel-body"><p class="small muted">支持 stdio MCP 的 Agent 可使用本机配置。rebuild_* 可构建、导出和采用；此入口不提供任意命令、安装或授权修改。</p>${code(JSON.stringify(i.mcp,null,2))}${btn(icon('copy')+'复制 MCP JSON','copy-mcp')}</div>`)}</div><div>${panel('Codex 配置片段',`<div class="panel-body"><p class="small muted">手动接入可将此片段合并到宿主支持的配置中。已有同名服务时先检查，不要重复覆盖。</p>${code(i.codex_toml)}${btn(icon('copy')+'复制 TOML','copy-toml')}</div>`)}
 ${panel('接入检查',`<div class="panel-body"><div class="field"><span class="field-label">实际管理器路径</span><div class="field-value mono">${esc(boot.app_dir)}</div></div><div class="field"><span class="field-label">管理数据目录</span><div class="field-value mono">${esc(boot.data_dir)}</div></div><p class="small muted">路径移动后重新生成配置。注册来源、宿主安装、工具可调用是三个不同状态，需要分别核对。</p>${btn(icon('shield')+'检查当前环境','doctor')}</div>`)}</div></div>`;}
async function updates(){const v=await api('versions');main.innerHTML=releaseView(boot,v,{head,panel,esc,badge,btn,time,packageRow});
 await mountSoftwareUpdate(document.querySelector('#software-update-host'));
 document.querySelector('#package-upload').addEventListener('change',async e=>{try{toast('正在检查扩展工具包…');importPlan=await upload(e.target.files[0]);importModal();}catch(x){toast(x.message,true);}e.target.value='';});}

function importModal(){const p=importPlan;modal('检查工具包与变更',`<div class="package-title"><strong>${esc(p.source==='builtin'?'内置 PPT 制作工具':p.name)}</strong>${p.source==='builtin'?badge('随软件更新'):badge('v'+p.version,'blue')}</div><p class="small muted">${esc(p.description)}</p>${notice(p.warning,true)}${p.compatibility?notice(p.compatibility.message,p.compatibility.status!=='compatible'):''}<div class="status-line">${badge(p.integrity==='manifest_verified'?'MANIFEST 完整性通过':'无文件清单 · 需自行核对',p.integrity==='manifest_verified'?'green':'amber')}${badge(p.file_count+' 个文件')}</div><p class="small muted">与当前包比较：新增 ${p.changes.added.length}，修改 ${p.changes.changed.length}，移除 ${p.changes.removed.length}。不同包名称之间仅作目录差异参考。</p>${code(['新增',...p.changes.added.slice(0,30),'','修改',...p.changes.changed.slice(0,30),'','移除',...p.changes.removed.slice(0,30)].join('\n'))}<p class="tiny muted break">ZIP SHA-256 · ${esc(p.archive_sha256)}</p>`,btn('确认导入 · 保持停用','commit-import',p.compatibility?.status==='incompatible'?'disabled':'','primary'));}
let directoryPicking=false;
function directoryField(id,field,label,value){return `<label class="field-label" for="${id}">${label}</label><div style="display:flex;gap:10px"><input type="text" id="${id}" value="${esc(value)}" title="${esc(value)}" placeholder="点击浏览选择文件夹" readonly style="flex:1;min-width:0">${btn('浏览…','pick-directory',`data-field="${field}" data-input="${id}" aria-label="浏览${label}"` )}</div>`;}
async function settingPage(){settings=await api('settings');settings.display_projects_directory=settings.projects_directory||boot.storage?.default_projects_root||'';main.innerHTML=head('设置','选择默认项目位置。临时指定其他目录时，Agent 会在该目录中完成整个项目。',btn(icon('check')+'保存设置','save-settings','','primary'))+
 panel('PPT 项目目录',`<div class="panel-body">${directoryField('setting-projects-directory','projects_directory','默认项目根目录',settings.display_projects_directory)}<p class="small muted">没有指定位置时，每个任务在这里新建独立项目文件夹。点击浏览选择，完整路径会自动显示。</p><p class="small muted">用户临时指定的目录优先于此设置。素材、制作版本、预览、修改记录和最终成品都保存在本项目内，成品按版本存入 delivery。</p><p class="small muted">切换项目只切换当前项目上下文。下方的工具箱程序与管理数据位置保持不变。</p><p id="directory-status" class="small muted" role="status">保存后，概况和新建制作的提示词会带入此目录，已有项目保持原位置。</p>${btn('安装与迁移','storage-setup')}</div>`)+
 panel('工具箱运行位置',`<div class="panel-body"><div class="field"><span class="field-label">程序、Skill 与工具</span><div class="field-value mono">${esc(boot.app_dir)}</div></div><div class="field"><span class="field-label">全局配置、日志与运行状态</span><div class="field-value mono">${esc(boot.data_dir)}</div></div><p class="small muted">这两处位置由安装与迁移维护，切换 PPT 项目时保持不变。</p></div>`)+
 `<section id="agent-setup" class="panel"></section><div class="setting-grid"><div>${panel('界面与管理记录',`<div class="panel-body"><div class="form-row"><div class="form-info"><strong>界面主题</strong><p>应用于当前浏览器管理界面。</p></div><select id="setting-theme" aria-label="界面主题"><option value="light">浅色</option><option value="dark">深色</option></select></div><div class="form-row"><div class="form-info"><strong>日志默认显示条数</strong><p>设置每次读取的条数，不自动删除历史记录。</p></div><input id="setting-log-size" type="number" min="20" max="1000" value="${settings.log_page_size}" style="width:90px" aria-label="日志显示条数"></div></div>`)}
 ${panel('素材使用权限',`<div class="panel-body"><p>保存后，Agent 会沿用允许的操作，无需逐次同意。项目可单独覆盖。使用宿主已配置的服务，不自动购买额度或开通新的付费服务。</p><div class="form-row"><strong>联网查找素材</strong>${switcher(settings.material_search_allowed,'setting','id="setting-material-search"','联网查找素材')}</div><div class="form-row"><strong>上传必要参考局部</strong>${switcher(settings.reference_upload_allowed,'setting','id="setting-reference-upload"','上传必要参考局部')}</div><div class="form-row"><div class="form-info"><strong>使用生成图片</strong><p>使用宿主已配置的生图工具。插图先绘制，Agent 判断相似度低于 75% 可转入生图；用户明确要求优先。支持透明背景与同图多图标裁剪。</p></div>${switcher(settings.host_generation_allowed,'setting','id="setting-generation"','使用生成图片')}</div></div>`)}
 ${panel('制作 Agent 权限',`<div class="panel-body"><div class="form-row"><div class="form-info"><strong>自动批准新项目请求</strong><p>按已保存规则批准新项目及本次输入目录。已拒绝或归档的申请保持原状态。关闭后新请求需手动批准，既有授权保留。</p></div>${switcher(settings.auto_approve_project_requests,'setting','id="setting-auto-approve"','自动批准新项目请求')}</div><div class="form-row"><div class="form-info"><strong>允许制作 Agent 执行工具</strong><p>控制受管 MCP 与 CLI 的制作调用，同时检查项目授权和工具启停。驻留 PPTAgent 在其接入页单独启用。</p></div>${switcher(settings.agent_execution_enabled,'setting','id="setting-exec"','允许制作 Agent 执行工具')}</div><div class="form-row"><div class="form-info"><strong>允许联网评测入口</strong><p>仅解除 bench.run 的管理器阻断；原评测预算、联网和图片上传确认仍然需要。</p></div>${switcher(settings.network_benchmarks_enabled,'setting','id="setting-network"','允许联网评测入口')}</div></div>`)}
 ${panel('执行环境',`<div class="panel-body"><div class="form-row paths"><div class="form-info"><strong>核心 Python 路径</strong><p>留空使用启动管理器的 Python。仅在运行诊断或受管工具时调用。</p></div><input type="text" id="setting-python" aria-label="核心Python路径" value="${esc(settings.python_path)}" placeholder="使用当前 Python"></div><div class="form-row paths"><div class="form-info"><strong>PowerShell 路径</strong><p>配置会传给工作流内部渲染。留空优先使用固定安装位置的 PowerShell 7，再查 PATH。</p></div><input type="text" id="setting-powershell" aria-label="PowerShell路径" value="${esc(settings.powershell_path)}" placeholder="优先 PowerShell 7"></div></div>`)}</div><aside>${panel('数据与备份',`<div class="panel-body"><div class="field"><span class="field-label">管理数据</span><div class="field-value mono">${esc(boot.data_dir)}</div></div><p class="small muted">配置、指令历史、项目索引、手动顺序和日志保存在管理数据中。项目文件与工作链记录留在各自文件夹，升级沿用原数据。</p>${btn(icon('download')+'导出管理配置','export-config','','full')}<p class="tiny muted">导出包含本机路径、指令覆盖和最近日志，不包含 PPT 项目。分享前仍需检查隐私内容。</p></div>`)}${panel('项目与工作链',`<div class="panel-body"><p>项目页提供手动排序、批量归档和批量交付。归档项目及成品统一在已归档页查看。</p><p>制作 Agent 在大阶段切换时打卡，阶段内由软件记录调用与文件变化。</p><a href="#/projects">管理项目 →</a><p><a href="#/pptagent">驻留 PPTAgent 接入 →</a></p></div>`)}</aside></div>`;document.querySelector('#setting-theme').value=settings.theme;await mountAgentSetup(document.querySelector('#agent-setup'));settingsNavigation();}
async function logs(query='',status=''){const list=await api('logs',undefined,{query,status});window.logRows=list;main.innerHTML=head('运行日志','查看管理操作与受管 Agent 调用；不监控直接运行的脚本或 Codex 的全部历史。',btn(icon('download')+'导出配置与日志','export-config'))+
 `<div class="toolbar"><div class="search">${icon('search')}<input id="log-search" placeholder="搜索操作或消息…" aria-label="搜索日志" value="${esc(query)}"></div><select id="log-status" aria-label="日志状态"><option value="">全部状态</option><option value="ok">已完成</option><option value="waiting">待处理</option><option value="error">错误</option></select>${btn('查询','filter-logs')}<span class="grow"></span><span class="tiny muted">最近 ${list.length} 条 · 本机时间</span></div><div class="panel"><table class="tool-table log-table"><thead><tr><th style="width:155px">时间</th><th class="source-col" style="width:90px">来源</th><th>操作与消息</th><th style="width:80px">状态</th></tr></thead><tbody>${list.map(l=>`<tr data-action="log-detail" data-id="${l.id}"><td class="log-time">${time(l.time)}</td><td class="source-col tiny muted">${esc(l.source)}</td><td><div class="log-message">${esc(l.message)}</div><div class="log-action">${esc(l.action)}</div></td><td>${badge(l.status==='error'?'错误':l.status==='waiting'?'待处理':'已完成',l.status==='error'?'red':l.status==='waiting'?'amber':'green')}</td></tr>`).join('')}</tbody></table>${!list.length?'<div class="empty">没有匹配的日志</div>':''}<div class="muted-line">常见密钥与认证字段会自动遮蔽，但日志脱敏不能保证移除所有业务敏感内容；分享前仍需检查。</div></div>`;document.querySelector('#log-status').value=status;document.querySelector('#log-search').addEventListener('keydown',e=>{if(e.key==='Enter')logs(e.target.value,document.querySelector('#log-status').value);});}
async function environmentModal(){toast('正在检测本机环境…');const d=await api('doctor',{});modal('环境检测结果',d.checks.map(c=>`<div class="list-row"><div class="list-main"><strong>${esc(c.name)}</strong><p class="break">${esc(c.detail)}</p></div>${badge(({passed:'检查通过',detected:'已发现',missing:'未发现',not_run:'未实测'})[c.status]||c.status,c.status==='passed'?'green':c.status==='missing'?'amber':'')}</div>`).join('')+'<div class="spacer"></div>'+notice(d.scope),btn('运行工具目录诊断','diagnostic','data-kind="registry"','primary'));}
async function action(e){if(e.target.closest('[data-usage-link]'))return;const b=e.target.closest('[data-action]');if(!b)return;if(b.closest('tr')&&e.target.closest('.switch'))return;const a=b.dataset.action;e.preventDefault();
 try{
 if(a==='discard-navigation'){unsavedChanges=false;dialog.close();location.hash=pendingNavigation;return;}
 if(a==='save-navigation'){if(route==='overview'){await saveOverview();if(!unsavedChanges){dialog.close();location.hash=pendingNavigation;}return;}const target=main.querySelector('[data-action="save-settings"],[data-action="save-doc"]');if(target){await action({target,preventDefault(){}});if(!unsavedChanges){dialog.close();location.hash=pendingNavigation}}return;}
 if(a==='storage-setup'){if(b.disabled)return;b.disabled=true;await api('storage.setup',{});toast('已请求打开安装与迁移窗口');return;}
 if(a==='pick-directory'){
  if(directoryPicking)return;directoryPicking=true;b.disabled=true;
  const input=document.getElementById(b.dataset.input),label=b.textContent;b.textContent='选择中…';
  try{
   const selected=await api('storage.pick-directory',{field:b.dataset.field,initial:input.value});
   if(selected.cancelled||!input.isConnected)return;
   input.value=selected.path;input.title=selected.path;
   document.querySelector('#directory-status').textContent='目录已选择，保存后会更新新建制作中的提示词。';
  }finally{directoryPicking=false;b.textContent=label;b.disabled=false;}
  return;
 }
 if(a.startsWith('go-')){location.hash='#/'+a.slice(3);return;}
 if(a==='close'){dialog.close();return;}if(a==='menu'){document.querySelector('#sidebar').classList.toggle('open');return;}if(a==='refresh'){if(unsavedChanges){toast('请先保存或撤销当前修改，再刷新',true);return;}if(route==='workbench'&&main.querySelector('.project-chain')){await refreshWorkbench();return;}await render();toast('数据已刷新');return;}
 if(a==='show-paths'){modal('存储位置',`<div class="field"><span class="field-label">程序与随包核心</span><div class="field-value mono">${esc(boot.app_dir)}</div></div><div class="field"><span class="field-label">管理数据（独立保存）</span><div class="field-value mono">${esc(boot.data_dir)}</div></div>${notice('升级程序时保留管理数据目录。这里不保存或移动你的 PPT 项目。')}`);return;}
 if(a==='doctor'){await environmentModal();return;}if(a==='diagnostic'){b.disabled=true;const r=await api('diagnostic',{kind:b.dataset.kind});modal('代码诊断结果',notice('本次仅运行所选诊断；退出成功不代表Office或视觉通过。')+code(JSON.stringify(r,null,2)));return;}
 if(a==='tool-tab'){tab=b.dataset.tab;await tools();return;}if(a==='prev-tools'){page--;paintToolList();return;}if(a==='next-tools'){page++;paintToolList();return;}
 if(a==='select-tool'){selected=b.dataset.id;await track('tool',selected,'viewed');paintToolList();await toolDetail();return;}
 if(a==='copy-tool'){const t=window.currentTool;await copy(t.kind==='python'||t.kind==='powershell'?t.powershell_example:JSON.stringify(t,null,2));toast('已复制实际入口与调用说明');return;}
 if(a==='view-source'){const source=await api('source',undefined,{id:selected});modal('源代码 · '+source.entry,notice(source.scope)+(source.truncated?'<p class="small muted">文件较长，显示前200KB。</p>':'')+code(source.content));return;}
 if(a==='open-doc'||a==='select-doc'){if(a==='open-doc')docPackage=b.dataset.package||boot.active.id;docPath=b.dataset.path;editing=false;if(route!=='docs')location.hash='#/docs';else await docs();return;}
 if(a==='edit-doc'){editing=!editing;await docView();return;}if(a==='copy-doc'){await copy(doc.content);toast('已复制文档');return;}
 if(a==='save-doc'){b.disabled=true;doc=await api('doc.save',{path:doc.path,package_id:docPackage,content:document.querySelector('#doc-editor').value,revision:doc.revision});unsavedChanges=false;await docs();toast('用户覆盖已保存，原始文件未修改');return;}
 if(a==='diff-doc'){modal('与随包版本的差异',code(doc.diff||'当前已保存内容与原版一致。编辑器未保存内容不在此比较中。'));return;}
 if(a==='history-doc'){modal('恢复指令版本',notice('恢复会生成新的用户修订，不删除历史记录。')+`<div class="list-row"><div class="list-main"><strong>随包原版</strong></div>${btn('恢复原版','restore-doc','data-revision="0"')}</div>`+doc.history.filter(h=>h.revision!==0).map(h=>`<div class="list-row"><div class="list-main"><strong>修订 ${h.revision}</strong><p>${time(h.updated)}</p></div>${btn('恢复','restore-doc',`data-revision="${h.revision}"`)}</div>`).join(''));return;}
 if(a==='restore-doc'){await api('doc.save',{path:doc.path,package_id:docPackage,revision:doc.revision,restore_revision:Number(b.dataset.revision)});dialog.close();await docs();toast('已恢复并保留修订历史');return;}
 if(a==='new-command'){commandModal();return;}if(a==='edit-command'){commandModal(window.customCommands.find(x=>x.id===b.dataset.id));return;}
 if(a==='copy-command'){await copy(window.customCommands.find(x=>x.id===b.dataset.id).body);toast('指令已复制');return;}
 if(a==='save-command'){await api('command.save',{id:commandEditing?.id,title:document.querySelector('#cmd-title').value.trim(),description:document.querySelector('#cmd-description').value,body:document.querySelector('#cmd-body').value,enabled:document.querySelector('#cmd-enabled').checked,revision:commandEditing?.revision||0});dialog.close();tab='commands';if(route!=='tools')location.hash='#/tools';else await tools();toast('已保存指令，未执行内容');return;}
 if(a==='trust-package'){modal('确认工具包来源',notice('确认信任后，此包中的代码可在你启用执行时运行。完整性校验不证明作者身份，请先审阅来源和代码。',true),btn('我已核对来源，确认信任','confirm-trust',`data-id="${esc(b.dataset.id)}"`,'primary'));return;}
 if(a==='confirm-trust'){await api('package.trust',{id:b.dataset.id,acknowledge:true});dialog.close();await render();toast('已记录用户信任决定');return;}
 if(a==='activate-package'){modal('切换受管版本',notice('只切换受管 Skill / 工具包；保留旧版本、管理设置和各版本用户覆盖，不迁移或改动PPT项目。需先启用并信任此包。'),btn('确认切换','confirm-activate',`data-id="${esc(b.dataset.id)}"`,'primary'));return;}
 if(a==='confirm-activate'){await api('package.activate',{id:b.dataset.id});dialog.close();selected=null;docPath='SKILL.md';await render();toast('已切换受管版本；宿主上下文需刷新');return;}
 if(a==='commit-import'){b.disabled=true;await api('package.commit',{confirm_id:importPlan.confirm_id});dialog.close();await render();toast('已导入，保持停用和未信任');return;}
 if(a==='save-settings'){if(directoryPicking){toast('请先完成文件夹选择');return;}b.disabled=true;const work=document.querySelector('#setting-projects-directory').value.trim();settings=await api('settings.save',{revision:settings.revision,values:{theme:document.querySelector('#setting-theme').value,log_page_size:Number(document.querySelector('#setting-log-size').value),agent_execution_enabled:document.querySelector('#setting-exec').checked,auto_approve_project_requests:document.querySelector('#setting-auto-approve').checked,network_benchmarks_enabled:document.querySelector('#setting-network').checked,material_search_allowed:document.querySelector('#setting-material-search').checked,reference_upload_allowed:document.querySelector('#setting-reference-upload').checked,host_generation_allowed:document.querySelector('#setting-generation').checked,python_path:document.querySelector('#setting-python').value.trim(),powershell_path:document.querySelector('#setting-powershell').value.trim(),projects_directory:!settings.projects_directory&&work===settings.display_projects_directory?'':work}});unsavedChanges=false;await reloadBoot();await settingPage();if(dialog.open&&pendingNavigation&&document.querySelector('.dialog-head h2')?.textContent==='更改尚未保存'){dialog.close();location.hash=pendingNavigation;}toast('默认项目位置与制作提示词已更新');return;}
 if(a==='copy-startup-prompt'){b.disabled=true;const prompt=await api('startup-prompt');const input=document.querySelector('#startup-prompt');if(input)input.value=prompt.text;await copy(prompt.text);const status=document.querySelector('#prompt-status');if(status)status.textContent='已复制，包含当前保存的目录设置';toast('制作提示词已复制');return;}
 if(a==='export-config'){await download(await api('config.export',{}));toast('已导出管理配置，请检查隐私后再分享');return;}
 if(a==='export-integration'){await download(await api('integration.export',{}));toast('已导出本机配置，未修改宿主设置');return;}
 if(a==='copy-mcp'){await copy(JSON.stringify(window.integration.mcp,null,2));toast('已复制 MCP 配置');return;}if(a==='copy-toml'){await copy(window.integration.codex_toml);toast('已复制 TOML 配置');return;}
 if(a==='register-plan'){integrationPlan=await api('integration.plan',{});modal('预览 Codex 本地来源注册',notice(integrationPlan.notice,true)+`<div class="field"><span class="field-label">将修改的市场文件</span><div class="field-value mono">${esc(integrationPlan.target)}</div></div><p class="small muted">保留其他 ${integrationPlan.preserved_other_entries} 个插件条目。${integrationPlan.will_replace_own_entry?'将更新本插件已有来源。':'新增本插件来源。'}</p>`+code(JSON.stringify(integrationPlan.proposed,null,2)),btn('确认写入并备份','register-apply','','primary'));return;}
 if(a==='register-apply'){b.disabled=true;await api('integration.apply',{confirm_id:integrationPlan.confirm_id});dialog.close();await plugins();toast('本地来源已登记；请在 Codex 中安装并验证');return;}
 if(a==='filter-logs'){await logs(document.querySelector('#log-search').value,document.querySelector('#log-status').value);return;}
 if(a==='log-detail'){const l=window.logRows.find(x=>x.id===Number(b.dataset.id));modal('操作详情',`<p class="small">${esc(l.message)}</p><p class="tiny muted">${time(l.time)} · ${esc(l.source)} · ${esc(l.action)}</p>`+code(JSON.stringify(l.details,null,2)));return;}
 }catch(x){toast(x.message,true);}finally{if(b.isConnected)b.disabled=false;}
}
document.addEventListener('click',action);
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches('tr[data-action]'))action(e);});
document.addEventListener('change',async e=>{const d=e.target.dataset;try{if(d.change==='toggle-tool'){await api('toggle',{kind:'tool',target:d.id,enabled:e.target.checked});items=await api('tools');paintToolList();await reloadBoot();toast('已更新受管工具启停');}if(d.change==='toggle-package'){await api('toggle',{kind:'package',package_id:d.id,enabled:e.target.checked});await render();toast('已更新管理器内启停，宿主配置未改动');}}catch(x){e.target.checked=!e.target.checked;toast(x.message,true);}});
document.addEventListener('input',e=>{if(e.target.matches('#doc-editor,#setting-projects-directory,#setting-theme,#setting-log-size,#setting-python,#setting-powershell,#setting-exec,#setting-auto-approve,#setting-network,#setting-generation'))unsavedChanges=true;});
window.addEventListener('beforeunload',e=>{if(unsavedChanges){e.preventDefault();e.returnValue='';}});
window.addEventListener('hashchange',()=>{if(unsavedChanges){pendingNavigation=location.hash;history.replaceState(null,'',lastLocation);modal('更改尚未保存','<p>保存当前修改后继续，或放弃本次修改。</p>',btn('放弃并继续','discard-navigation')+btn('保存并继续','save-navigation','','primary'));return;}lastLocation=location.hash;render();});
new MutationObserver(()=>{if(['settings','skills','tools','plugins','updates','logs'].includes(route)&&!main.querySelector('.settings-navigation')&&main.querySelector('.page-head'))settingsNavigation();}).observe(main,{childList:true});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
render();
startAgentLive();
