export function releaseView(boot,v,{head,panel,esc,badge,btn,time,packageRow}){
 const version=v.product_version||boot.version;
 const builtin=v.packages.find(p=>p.source==='builtin');
 const extensions=v.packages.filter(p=>p.source!=='builtin');
 const distribution=v.distribution||boot.distribution;
 const softwareHistory=(v.software_history||[]).map(h=>`<div class="history-row"><div class="list-main"><strong>PPT Toolbox ${esc(h.version)}</strong><p>${h.kind==='first_observed'?'首次记录此软件版本':'检测到软件版本或构建变化'}</p><small class="muted">${time(h.observed_at)}</small></div></div>`).join('');
 const names=new Map(v.packages.map(p=>[p.id,p.source==='builtin'?'内置 PPT 制作工具':`${p.name} ${p.version}`]));
 const extensionHistory=v.history.map(h=>`<div class="history-row"><div class="list-main"><strong>${esc(names.get(h.new_id)||h.new_id)}</strong><p>原工具包 ${esc(names.get(h.old_id)||h.old_id)}</p><small class="muted">${time(h.time)}</small></div></div>`).join('');
 return head('版本与更新','软件与内置制作工具统一更新，扩展工具包单独管理。')+
 `<div class="release-layout"><div>${panel('当前软件',`<div class="panel-body"><div class="release-title"><strong>PPT Toolbox</strong>${badge(version,'blue')}</div><p>界面、项目管理、内置制作工具和随附说明使用同一发行版本。</p><p class="small muted">${distribution?'更新时请先结束正在运行的任务，再运行新版安装程序。沿用原安装位置、管理数据和项目目录。':'当前为源码预览，尚未安装此版本。正式安装的软件继续独立运行。'}</p><div class="actions"><a href="#/docs?path=manager_docs/CHANGELOG.md">查看更新内容</a><a href="#/docs?path=manager_docs/VERSIONS.md">版本与升级说明</a>${distribution?btn('安装位置与迁移','storage-setup'):''}</div></div>`)}
 ${panel('内置 PPT 制作工具',`<div class="panel-body"><div class="actions">${badge('随软件更新')}${badge(builtin?.enabled?'已启用':'已停用',builtin?.enabled?'green':'amber')}${builtin?.active?badge('当前使用','green'):badge('当前使用扩展工具包')}</div><p class="small muted">制作工作流、工具与 Agent 指令一起更新。</p><div class="actions">${btn('查看制作指令','open-doc','data-path="SKILL.md" data-package="builtin"')}${!builtin?.active?btn('使用内置工具','activate-package','data-id="builtin"'):''}<a href="#/skills">制作规则与权限</a></div></div>`)}
 ${panel('软件版本记录',`<div class="panel-body"><p class="small muted">从启用记录后开始保存软件启动时读到的版本，早期安装历史可能不完整。</p></div>${softwareHistory||'<div class="release-empty">暂无软件版本记录。源码预览不计入安装版本记录。</div>'}`)}</div>
 <aside>${panel('下载与安装更新',`<div class="panel-body" id="software-update-host" aria-live="polite">正在读取更新状态…</div>`)}
 <details class="panel release-diagnostics"><summary>诊断信息</summary><div class="panel-body"><dl><dt>软件发行版本</dt><dd>${esc(version)}</dd><dt>内置工具包</dt><dd>${esc(builtin?.name)} · ${esc(builtin?.version)}</dd><dt>接口协议</dt><dd>${esc(v.api_version||boot.api_version)}</dd><dt>代码指纹</dt><dd class="mono">${esc(distribution?.source_sha256||'源码预览，构建后生成')}</dd><dt>程序位置</dt><dd class="mono">${esc(boot.app_dir)}</dd></dl></div></details></aside></div>
 <details class="panel release-extensions" id="extension-management"><summary>扩展工具包管理 <span class="muted small">${extensions.length} 个已导入</span></summary><div class="panel-body"><p class="small muted">独立扩展保留自己的版本号。导入后先核对兼容范围与来源，再启用和切换。</p><div class="upload-zone"><strong>选择 ZIP 扩展工具包</strong><p>完整 Skill 或插件目录，最大 32 MB</p><input type="file" accept=".zip,application/zip" id="package-upload" aria-label="导入ZIP工具包"></div><p class="small muted">先检查文件清单、路径与完整性。导入后保持停用，代码执行仍需原有权限。</p></div>${extensions.length?extensions.map(packageRow).join(''):'<p class="release-empty">尚未导入扩展工具包，日常制作可直接使用内置工具。</p>'}<div class="panel-head"><h2>工具包切换记录</h2></div>${extensionHistory||'<p class="release-empty">尚未切换工具包。</p>'}</details>`;
}
